colorscheme wombat256mod
set cursorline
set directory=/tmp/nvim-swapfiles
set expandtab
set hidden
set ignorecase
set incsearch
set list
set number
set ruler
set shiftwidth=4
set smartcase
set smartindent
set so=5
set softtabstop=4
set undodir=~/.undodir/
set undofile
set undolevels=100
set undoreload=1000
set wildmode=longest,list,full
